//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR_Funds_MN
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FundEntities : DbContext
    {
        public FundEntities()
            : base("name=FundEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<full_valuestoprocedure> full_valuestoprocedure { get; set; }
        public virtual DbSet<fund_collection_new> fund_collection_new { get; set; }
        public virtual DbSet<fund_login> fund_login { get; set; }
        public virtual DbSet<trans_fund> trans_fund { get; set; }
        public virtual DbSet<avl_fund> avl_fund { get; set; }
        public virtual DbSet<fund_login_onlyfor_signup> fund_login_onlyfor_signup { get; set; }
        public virtual DbSet<loansof_member> loansof_member { get; set; }
        public virtual DbSet<new_addmember_only> new_addmember_only { get; set; }
        public virtual DbSet<funds_ofMember> funds_ofMember { get; set; }
        public virtual DbSet<valuesto_sp_funds_ofMember> valuesto_sp_funds_ofMember { get; set; }
    
        public virtual ObjectResult<sp_fund_login__Result> sp_fund_login_(string userName_)
        {
            var userName_Parameter = userName_ != null ?
                new ObjectParameter("userName_", userName_) :
                new ObjectParameter("userName_", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_fund_login__Result>("sp_fund_login_", userName_Parameter);
        }
    
        public virtual ObjectResult<string> sp_members()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_members");
        }
    
        public virtual ObjectResult<sp_view_fund_collection_new_Result> sp_view_fund_collection_new()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_view_fund_collection_new_Result>("sp_view_fund_collection_new");
        }
    
        public virtual ObjectResult<sp_view_fund_collection_new_byid_Result> sp_view_fund_collection_new_byid(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_view_fund_collection_new_byid_Result>("sp_view_fund_collection_new_byid", idParameter);
        }
    
        public virtual ObjectResult<sp_viewtrans_fund_Result> sp_viewtrans_fund()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_viewtrans_fund_Result>("sp_viewtrans_fund");
        }
    
        public virtual int sp_fund_collection_new_addmember(Nullable<int> id, string name, Nullable<long> mobile_no, Nullable<System.DateTime> dt, ObjectParameter idout)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var mobile_noParameter = mobile_no.HasValue ?
                new ObjectParameter("mobile_no", mobile_no) :
                new ObjectParameter("mobile_no", typeof(long));
    
            var dtParameter = dt.HasValue ?
                new ObjectParameter("dt", dt) :
                new ObjectParameter("dt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_fund_collection_new_addmember", idParameter, nameParameter, mobile_noParameter, dtParameter, idout);
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_fund_amount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_fund_amount");
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_checkbal()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_checkbal");
        }
    
        public virtual ObjectResult<Nullable<int>> sp_no_ofdays(ObjectParameter recnt_date, string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_no_ofdays", recnt_date, nameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_no_ofweeks(string name, Nullable<System.DateTime> date)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_no_ofweeks", nameParameter, dateParameter);
        }
    
        public virtual int sp_fund_collection_new(Nullable<int> id, string name, Nullable<long> mobile_no, Nullable<decimal> loan_amt, Nullable<decimal> inst_amt, Nullable<int> no_ofdue, Nullable<System.DateTime> dt, ObjectParameter trans_type, ObjectParameter sl_no, ObjectParameter avl_bal)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var mobile_noParameter = mobile_no.HasValue ?
                new ObjectParameter("mobile_no", mobile_no) :
                new ObjectParameter("mobile_no", typeof(long));
    
            var loan_amtParameter = loan_amt.HasValue ?
                new ObjectParameter("loan_amt", loan_amt) :
                new ObjectParameter("loan_amt", typeof(decimal));
    
            var inst_amtParameter = inst_amt.HasValue ?
                new ObjectParameter("inst_amt", inst_amt) :
                new ObjectParameter("inst_amt", typeof(decimal));
    
            var no_ofdueParameter = no_ofdue.HasValue ?
                new ObjectParameter("no_ofdue", no_ofdue) :
                new ObjectParameter("no_ofdue", typeof(int));
    
            var dtParameter = dt.HasValue ?
                new ObjectParameter("dt", dt) :
                new ObjectParameter("dt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_fund_collection_new", idParameter, nameParameter, mobile_noParameter, loan_amtParameter, inst_amtParameter, no_ofdueParameter, dtParameter, trans_type, sl_no, avl_bal);
        }
    
        public virtual ObjectResult<sp_viewtrans_bydate_Result> sp_viewtrans_bydate(Nullable<System.DateTime> date)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_viewtrans_bydate_Result>("sp_viewtrans_bydate", dateParameter);
        }
    
        public virtual ObjectResult<sp_view_fund_collection_new_byname_Result> sp_view_fund_collection_new_byname(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_view_fund_collection_new_byname_Result>("sp_view_fund_collection_new_byname", nameParameter);
        }
    
        public virtual ObjectResult<sp_viewmembers_Result> sp_viewmembers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_viewmembers_Result>("sp_viewmembers");
        }
    
        public virtual ObjectResult<string> sp_members_singlename(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_members_singlename", nameParameter);
        }
    
        public virtual int sp_avl_fund(Nullable<decimal> avl_fund_)
        {
            var avl_fund_Parameter = avl_fund_.HasValue ?
                new ObjectParameter("avl_fund_", avl_fund_) :
                new ObjectParameter("avl_fund_", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_avl_fund", avl_fund_Parameter);
        }
    
        public virtual int sp_fund_collection_new_editonly(Nullable<int> id, string name, Nullable<long> mob_no)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var mob_noParameter = mob_no.HasValue ?
                new ObjectParameter("mob_no", mob_no) :
                new ObjectParameter("mob_no", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_fund_collection_new_editonly", idParameter, nameParameter, mob_noParameter);
        }
    
        public virtual ObjectResult<sp_view_fund_collection_new_byidonly_Result> sp_view_fund_collection_new_byidonly(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_view_fund_collection_new_byidonly_Result>("sp_view_fund_collection_new_byidonly", idParameter);
        }
    
        public virtual ObjectResult<sp_fund_login_Result> sp_fund_login(string userName_)
        {
            var userName_Parameter = userName_ != null ?
                new ObjectParameter("userName_", userName_) :
                new ObjectParameter("userName_", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_fund_login_Result>("sp_fund_login", userName_Parameter);
        }
    
        public virtual int sp_fund_login_insert(Nullable<int> sl_no, string username, string pass_word, Nullable<int> user_roleid, string name, ObjectParameter sl_noout)
        {
            var sl_noParameter = sl_no.HasValue ?
                new ObjectParameter("sl_no", sl_no) :
                new ObjectParameter("sl_no", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var pass_wordParameter = pass_word != null ?
                new ObjectParameter("pass_word", pass_word) :
                new ObjectParameter("pass_word", typeof(string));
    
            var user_roleidParameter = user_roleid.HasValue ?
                new ObjectParameter("user_roleid", user_roleid) :
                new ObjectParameter("user_roleid", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_fund_login_insert", sl_noParameter, usernameParameter, pass_wordParameter, user_roleidParameter, nameParameter, sl_noout);
        }
    
        public virtual ObjectResult<sp_view_fund_login_Result> sp_view_fund_login()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_view_fund_login_Result>("sp_view_fund_login");
        }
    
        public virtual int sp_fund_login_delete(Nullable<int> sl_no)
        {
            var sl_noParameter = sl_no.HasValue ?
                new ObjectParameter("sl_no", sl_no) :
                new ObjectParameter("sl_no", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_fund_login_delete", sl_noParameter);
        }
    
        public virtual int sp_deleteMember(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_deleteMember", idParameter);
        }
    
        public virtual ObjectResult<sp_viewtrans_fund_joined_deposit_Result> sp_viewtrans_fund_joined_deposit()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_viewtrans_fund_joined_deposit_Result>("sp_viewtrans_fund_joined_deposit");
        }
    
        public virtual int sp_loansof_member(Nullable<int> loan_id, Nullable<int> mem_id, string name, ObjectParameter loan_idout)
        {
            var loan_idParameter = loan_id.HasValue ?
                new ObjectParameter("loan_id", loan_id) :
                new ObjectParameter("loan_id", typeof(int));
    
            var mem_idParameter = mem_id.HasValue ?
                new ObjectParameter("mem_id", mem_id) :
                new ObjectParameter("mem_id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_loansof_member", loan_idParameter, mem_idParameter, nameParameter, loan_idout);
        }
    
        public virtual ObjectResult<sp_view_loansof_member_Result> sp_view_loansof_member(Nullable<int> mem_id)
        {
            var mem_idParameter = mem_id.HasValue ?
                new ObjectParameter("mem_id", mem_id) :
                new ObjectParameter("mem_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_view_loansof_member_Result>("sp_view_loansof_member", mem_idParameter);
        }
    
        public virtual ObjectResult<string> sp_members_checkname(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_members_checkname", nameParameter);
        }
    
        public virtual int sp_new_addmember_only(Nullable<int> id, string name, Nullable<long> mobile_no, Nullable<System.DateTime> dt, ObjectParameter idout)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var mobile_noParameter = mobile_no.HasValue ?
                new ObjectParameter("mobile_no", mobile_no) :
                new ObjectParameter("mobile_no", typeof(long));
    
            var dtParameter = dt.HasValue ?
                new ObjectParameter("dt", dt) :
                new ObjectParameter("dt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_new_addmember_only", idParameter, nameParameter, mobile_noParameter, dtParameter, idout);
        }
    
        public virtual ObjectResult<sp_view_new_addmember_only_Result> sp_view_new_addmember_only()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_view_new_addmember_only_Result>("sp_view_new_addmember_only");
        }
    
        public virtual ObjectResult<sp_view_new_addmember_byid_Result> sp_view_new_addmember_byid(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_view_new_addmember_byid_Result>("sp_view_new_addmember_byid", idParameter);
        }
    
        public virtual ObjectResult<sp_view_funds_ofMember_byid_Result> sp_view_funds_ofMember_byid(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_view_funds_ofMember_byid_Result>("sp_view_funds_ofMember_byid", idParameter);
        }
    
        public virtual int sp_funds_ofMember(Nullable<int> loan_id, Nullable<int> id, string name, Nullable<decimal> loan_amt, Nullable<decimal> inst_amt, ObjectParameter bal_amt, Nullable<int> no_ofdue, Nullable<System.DateTime> dt, ObjectParameter trans_type, ObjectParameter sl_no, ObjectParameter avl_bal, ObjectParameter loan_idout)
        {
            var loan_idParameter = loan_id.HasValue ?
                new ObjectParameter("loan_id", loan_id) :
                new ObjectParameter("loan_id", typeof(int));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var loan_amtParameter = loan_amt.HasValue ?
                new ObjectParameter("loan_amt", loan_amt) :
                new ObjectParameter("loan_amt", typeof(decimal));
    
            var inst_amtParameter = inst_amt.HasValue ?
                new ObjectParameter("inst_amt", inst_amt) :
                new ObjectParameter("inst_amt", typeof(decimal));
    
            var no_ofdueParameter = no_ofdue.HasValue ?
                new ObjectParameter("no_ofdue", no_ofdue) :
                new ObjectParameter("no_ofdue", typeof(int));
    
            var dtParameter = dt.HasValue ?
                new ObjectParameter("dt", dt) :
                new ObjectParameter("dt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_funds_ofMember", loan_idParameter, idParameter, nameParameter, loan_amtParameter, inst_amtParameter, bal_amt, no_ofdueParameter, dtParameter, trans_type, sl_no, avl_bal, loan_idout);
        }
    
        public virtual int sp_funds_ofMember_for_edit(Nullable<int> loan_id, string name)
        {
            var loan_idParameter = loan_id.HasValue ?
                new ObjectParameter("loan_id", loan_id) :
                new ObjectParameter("loan_id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_funds_ofMember_for_edit", loan_idParameter, nameParameter);
        }
    
        public virtual ObjectResult<sp_view_funds_ofMember_by_loanid_Result> sp_view_funds_ofMember_by_loanid(Nullable<int> loan_id)
        {
            var loan_idParameter = loan_id.HasValue ?
                new ObjectParameter("loan_id", loan_id) :
                new ObjectParameter("loan_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_view_funds_ofMember_by_loanid_Result>("sp_view_funds_ofMember_by_loanid", loan_idParameter);
        }
    
        public virtual int sp_delete_funds_ofMember_by_loanid(Nullable<int> loan_id)
        {
            var loan_idParameter = loan_id.HasValue ?
                new ObjectParameter("loan_id", loan_id) :
                new ObjectParameter("loan_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_delete_funds_ofMember_by_loanid", loan_idParameter);
        }
    
        public virtual ObjectResult<sp_viewtrans_fund_joined_deposit_byId_Result> sp_viewtrans_fund_joined_deposit_byId(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_viewtrans_fund_joined_deposit_byId_Result>("sp_viewtrans_fund_joined_deposit_byId", idParameter);
        }
    }
}
