//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR_Funds_MN
{
    using System;
    using System.Collections.Generic;
    
    public partial class fund_login_onlyfor_signup
    {
        public int sl_no { get; set; }
        public string username { get; set; }
        public string pass_word { get; set; }
        public string con_pass_word { get; set; }
        public Nullable<int> user_roleid { get; set; }
        public string Name { get; set; }
    }
}
