//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR_Funds_MN
{
    using System;
    using System.Collections.Generic;
    
    public partial class new_addmember_only
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<long> mobile_no { get; set; }
        public Nullable<System.DateTime> dt { get; set; }
    }
}
