//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR_Funds_MN
{
    using System;
    using System.Collections.Generic;
    
    public partial class valuesto_sp_funds_ofMember
    {
        public int loan_id { get; set; }
        public Nullable<int> id { get; set; }
        public string name { get; set; }
        public Nullable<decimal> loan_amt { get; set; }
        public Nullable<decimal> inst_amt { get; set; }
        public Nullable<int> no_ofdue { get; set; }
        public Nullable<System.DateTime> paid_dt { get; set; }
    }
}
